BEGIN TRANSACTION;
PRAGMA foreign_keys = OFF;
CREATE TABLE history (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, no INTEGER, result TEXT, datetime TIMESTAMP, sampleid INTEGER, FOREIGN KEY (sampleid) REFERENCES sample (Id));
CREATE TABLE sample (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, Type INTEGER);
END TRANSACTION;
